### ISSUE TITLE
Some items massive with texturepack

### ISSUE THREAD

**Issue by Breadabix** [Davoleo/Metallurgy-4-Reforged#350] opened 2022-02-17 11:45 UTC
Using 1.3.0 along with a 64x texturepack some armour and tool textures actually increase in size in the inventory. It doesnt matter if metallurgy is the only mod installed or one of many, and its always the same items that get bigger.
![2022-02-17_11 28 18](https://user-images.githubusercontent.com/19786108/154474979-a0217055-3469-4bef-b0ab-65ef1de92f38.png)
.

**Comment by Klazkin** [comment] 2022-02-19 14:22
Yes, this is caused by a custom model overwrite that I use to remove the usual 16x16 size limit without changing the relative size of the pixels (see picture). It is not something I we can fix on our side, but it can be relatively easily fixed by overwriting our `extended.json` model file through resource-pack models, located [here](https://github.com/Davoleo/Metallurgy-4-Reforged/blob/master/src/main/resources/assets/metallurgy/models/item/extended.json).

What you are looking for is basically the whole `"display": {`, tag removing it (and everything contained in it) will make extended items display exactly like normal ones.

![image](https://user-images.githubusercontent.com/44501483/154804725-461aff08-2891-4caa-a495-5bad57c02796.png)

**Closed by Klazkin** 2022-02-19 14:22 UTC
Labels: bug, external cause
