### ISSUE TITLE
Alteration to Tinkers Construct integration 

### ISSUE THREAD

**Issue by SextupleTap** [Davoleo/Metallurgy-4-Reforged#153] opened 2019-05-07 23:15 UTC
**Describe the solution you'd like** <br>
Allow for all alloys and metals that have in game tools/armor (or maybe even materials that still don't have tools anyways but disabled by default?) to be made into tinkers tools again (potentially reverting the changes made in 0.2.0), then allow for metallurgy tinker materials to be disabled within the configs.

Extra: More advanced configurations such as material stats and which tinkers parts are allowed to be made form a specific material can be left for in-mod Craft Tweaker integration (noticed it was in your checklist) or external configuration with Tweakers Construct (or other similar mods).

On the subject of what was stated earlier about "potentially reverting the changes made in 0.2.0," obviously all of you, the developers, it's your mod and you can have certain materials disabled by default to provide the default experience you want for the players who play with your mod, the "unlocking all materials" just opens up more customization and development capabilities.

**Why would you like this to be implemented?** <br>
This alteration to tinkers integration will allow for greater customization and re-balancing  capabilities for the development of mod packs. It also will eliminate material restrictions and on top of the two previous examples it will altogether provide more freedom to the players.

**Describe alternatives you've considered** (optional)  <br>
(The "Extra:" section of the suggestion description)

**Additional context** (optional) <br>
The summary is just unlocking all the materials for tinkers integration, and placing the enabling/disabling of metallurgy tinker materials in the configs, which then allows for additional mods to configure stats and allowed tool parts etc. 😄

**Comment by P3rf3ctXZer0** [comment] 2019-05-21 23:42
I second this feature as I am getting problem with orespawn and MMDlib reg.

**Comment by P3rf3ctXZer0** [comment] 2019-05-21 23:43
`net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Armory Expansion - Construct's Armory (armoryexpansion-conarm)
Caused by: slimeknights.tconstruct.library.TinkerAPIException: [TCon API] Could not add Stats to "prometheum": Stats of type "core" were already registered by Metallurgy 4: Reforged. Use the events to modify stats.
	at slimeknights.tconstruct.library.TinkerRegistry.error(TinkerRegistry.java:951)
	at slimeknights.tconstruct.library.TinkerRegistry.addMaterialStats(TinkerRegistry.java:232)
	at org.softc.armoryexpansion.integration.plugins.constructs_armory.ConArmStats.registerMaterialArmorStats(ConArmStats.java:30)
	at org.softc.armoryexpansion.integration.plugins.constructs_armory.ConArmStats.registerMaterialArmorStats(ConArmStats.java:45)
	at org.softc.armoryexpansion.integration.plugins.constructs_armory.ConArmStats.registerMaterialArmorStats(ConArmStats.java:49)
	at org.softc.armoryexpansion.integration.plugins.tinkers_construct.TiCMaterial.registerTinkersMaterialStats(TiCMaterial.java:283)
	at org.softc.armoryexpansion.integration.aelib.AbstractIntegration.lambda$registerMaterialStats$6(AbstractIntegration.java:283)
	at java.util.HashMap$Values.forEach(Unknown Source)
	at org.softc.armoryexpansion.integration.aelib.AbstractIntegration.registerMaterialStats(AbstractIntegration.java:282)
	at org.softc.armoryexpansion.integration.aelib.AbstractIntegration.preInit(AbstractIntegration.java:47)
	at org.softc.armoryexpansion.integration.ConArmIntegration.preInit(ConArmIntegration.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)`

**Comment by P3rf3ctXZer0** [comment] 2019-05-21 23:53
removed mod - does not play nice with others.

**Comment by Davoleo** [comment] 2019-05-22 06:56
This suggestion is not related at all to the issue you're talking about
@P3rf3ctXZer0

**Comment by HurtsAsHell** [comment] 2019-05-22 13:55
furthermore you did not follow the guide line to use PASTEBIN for the CRASHLOG.
so thank you for telling us that you removed the mod, we'll put it in our notebook

**Comment by Davoleo** [comment] 2019-05-25 15:55
We've talked about it and decided to avoid opening up all tool materials to tinker integration for many reasons:

- Materials that had their tinker counter-parts before 0.2.0 were materials that didn't have neither armor or tool sets in the mod itself, and we decided to disable them partially because of that
- The ones we partially removed weren't supposted to be there since the beginning
- Having them partially removed doesn't afflict the gameplay much
- As an abstract concept this mod, shouldn't be considered merely as a Tinkers' Contruct Addon

Although your suggestion indeed has a pro and that is: 
- to give more customization options to modpack developers and players

However I don't think they'll be that much limited with just a few missing tool materials

So I'm going to close this issue...
further discussion is however accepted 👍

**Closed by Davoleo** 2019-05-25 15:55 UTC
Labels: suggestion
