### ISSUE TITLE
[1.12.2] Game freezes if you equip certain Construct's Armory Pieces with different traits if Tinkers Leveling is installed.

### ISSUE THREAD

**Issue by Z-Tunic** [Davoleo/Metallurgy-4-Reforged#147] opened 2019-04-23 11:08 UTC
**Describe the bug**
Attempting to wear certain Construct's Armory pieces with different traits will cause the game to freeze. Only way to exit is to kill the process via task manager.

**To Reproduce**
1. Equip two pieces of all Kalendrite OR Amorine with the trait 'Strength'. Game will freeze upon equipping the second piece.

2. Equip something such as a Manyullyn Leggins (Manyullun Leggins Core, Steel Plates and Cobalt Trim.) These grant 'Vengeful', 'Indomitable' and 'Lightweight' traits. Game will freeze upon equipping them.

**Expected behavior**
The game not freezing.

**Versions:**
- Metallurgy 4: Reforged: 0.2.0
- Forge: 14.23.5.2836
- Minecraft: 1.12.2
- Conflicting mod _(if regarding mod integration)_: TinkerToolLeveling-1.12.2-1.1.0

**Additional context**
Unsure if Modifiers could also cause a freeze to happen. No crash occurs so it's just a complete lock-up with no crash report. The log doesn't appear to say anything when the freeze occurs.

If either Metallurgy or Tinker's Tool Leveling are used by themselves... the game will not freeze while equipping certain armor pieces.

Mod List:
conarm-1.12.2-1.2.3.3
Mantle-1.12-1.3.3.49
Metallurgy-4-Reforged-0.2.0
TConstruct-1.12.2-2.12.0.135
TinkerToolLeveling-1.12.2-1.1.0

**Comment by Davoleo** [comment] 2019-04-23 11:37
Ok, I was able to reproduce this in my dev environment, but rn I'm quite unsure of what is going wrong :P

It's a really weird bug, especially because you don't get any log info, or any kind of errors

We'll further look into this for sure though, thanks for reporting
(PS: if you get some more info that you think might help us to sort this out feel free to add it here!)

**Comment by Syphenion** [comment] 2019-04-23 13:28
Yeah that's the same bug I had previously.

**Comment by Davoleo** [comment] 2019-04-23 13:32
mmh, however @Z-Tunic has said this bug doesn't seem to be reproduceable if you remove Tinkers Tool Leveling 🤔 
@Syphenion

**Comment by Z-Tunic** [comment] 2019-04-23 13:49
I tried without TinkerToolLeveling and was able to equip the mentioned armors without any freezes. Unless there's certain other armors that cause a freeze that isn't related to TinkerToolLeveling?

Speaking of which, I forgot to update ConArm to a later version "conarm-1.12.2-1.2.3.4". Did just that and tried the steeps again. Still get the same freeze when trying to wear... say two pieces of ConArm Kalendrite Armor with 'Strength' but if I remove TinkersToolLeveling? No freeze. If I remove Metallurgy instead of TinkersToolLeveling? No freeze.

-----

Alrighty... so if you wear an all-Steel piece, all-Manyullyn piece, and a all-Cobalt piece (Steel Chestplate, Manyullyn Leggings, and Cobalt Boots. Traits: Steady, Indomitable, Vengeful, Prideful, Featherweight, and Lightweight). No freeze occurs when wearing the pieces.

Now if I mix the parts into one armor piece. Let's just say a Manyullyn Chestplate Core, Steel Plates, and Cobalt Trim. (Vengeful, Lightweight, and Indomitable). Game freezes.

Perhaps maybe it doesn't like it when the parts are mixed up? Then again why would Strength alone freeze? Unless it tries to apply a Strength II? I dunno.

**Comment by Davoleo** [comment] 2019-04-23 13:54
uh, thanks for investigating more into this

**Comment by Davoleo** [comment] 2019-04-23 13:55
this kind of freeze with no errors however makes me think it should be stuck in some while/for loop

**Comment by Z-Tunic** [comment] 2019-04-23 13:58
@Syphenion 
I tried an all-Steel Chestplate with the 'Traveler's Cloak (Slowfall)' and that too causes a freeze, even if TinkersToolLeveling isn't installed so I guess certain modifiers can apparently cause a freeze to happen.

This freeze doesn't occur if I put the Traveler's Cloak (Slowfall) on a all-Cobalt Chestplate. Now I'm really puzzled.

**Comment by Davoleo** [comment] 2019-04-23 14:00
ok so this is related to #142

**Comment by slushieboy99** [comment] 2019-04-29 17:40
Let me know when this is patched, I am also having this issue

**Comment by HurtsAsHell** [comment] 2019-04-29 17:51
When the 2.1 will be released it will be fixed

> Let me know when this is patched, I am also having this issue

**Comment by slushieboy99** [comment] 2019-04-29 20:15
Thanks! I'll keep an eye out for that.

**Comment by ReducoGD** [comment] 2019-05-01 01:26
I had the same problem, but with other parts:
-Krik plates.
-Lutetium armor cores.
-Amordine trims.

I guessed that the freezing was caused by the armor pieces being equipped, each one trying to apply the Strength II effect on the player (because of the Amordine trims's trait).

**Comment by SextupleTap** [comment] 2019-05-07 22:51
I can confirm that this type of bug happens without tinkers tool leveling as well.

The way I did it was having one of the armor cores (it doesn't matter it can be the helmet, chest plate, leggings, or boots) that is made of slime, and then any Construct's Armory pieces (it doesn't matter what the trim material or plate material is) that has a slime core piece, upon equipping it, the game will freeze/soft lock without producing a crash log, and you can only kill it by spamming the x button on the tab or killing it with task manager.

**Closed** 2019-05-28 17:22 UTC
Labels: (╯°□°）╯︵ ┻━┻, bug, fixed/implemented in dev

**Comment by ekoman93** [comment] 2019-05-29 19:24
it also freezes when I mixed wood and stone parts for any of the pieces
stone cores and trim with wood plates

**Comment by Davoleo** [comment] 2019-05-29 19:52
yep, it's fixed in our dev version, it'll be fixed as soon as we publish a new release
