### ISSUE TITLE
 new textures have too much contrast

### ISSUE THREAD

**Issue by RCXcrafter** [Davoleo/Metallurgy-4-Reforged#119] opened 2019-03-04 20:05 UTC
The improved versions of the textures are pretty good but the contrast on them is way too high. Quite a few of the color schemes go from almost black to almost white which looks way too harsh. Most of the ores don't have this issue and some are even a bit on the low contrast side. I also think some metals could use a bit more saturation. Besides that the new textures are definitely an improvement.

If you'd like I could change the textures myself and make a pull request.

**Comment by Klazkin** [comment] 2019-03-04 20:47
![untitled](https://user-images.githubusercontent.com/44501483/53760269-0aae7780-3ecb-11e9-8d96-490cf9bae50d.png)
Here's a sheet of all of the metals in the mod, I would appreciate if you could either mark which ones you don't like or tell me here. It would save me quite a bit of time, since from what I could tell, you said that only a few metals need changes :P  (Don't take armour textures into consideration, those might be changing anyway)

I understand what you mean, and the saturation bit was already something I was very well aware of.
However, I won't change because I don't want metals to look too much alike. (for example, raising saturation on damascus would make it have a similar colour as oureclase and etc.. while I am already running out of colors to use for new possible planned metals)

Ores are different cause in some cases colour wasn't enough to differentiate metals where it matters most, so I have multiple presets for ore textures with varying amounts of contrast for all kinds of metals. While all other textures use pretty much the same method. 
Because of using a couple of special [techniques] to create these textures (https://media.discordapp.net/attachments/508384766241013764/529442476822495245/9e313c251c89bdc81389d90269414f2a.png), I doubt I can let you help me with texture changes, not because I think you lack artistic ability to do so.

**Comment by RCXcrafter** [comment] 2019-03-05 10:16
well, all of them have too much contrast, especially the blocks, ingots and dusts but the tools and armor as well.

I also think it would be a good idea to bring back the different shapes for the types of ores, with those you could easily see if it was a base, precious, fantasy or utility ore. The nether and end metals also had different shapes but those just looked cool.

I think the problem of metals looking similar to each other is mostly caused by the restrictions of your system for creating the color schemes. Personally I'd create a color scheme manually and apply it to the textures with the paint bucket like the way shadowclaimer made the original textures, but your method could be viable too. If you use paint.net or gimp I could take a look at the textures and get a better understanding of how they come together (if you're okay with sharing the source files of course).

Also, the tools handles also have the metal color scheme applied to them while they should be wooden.

I'll comment on all the metals from left to right (excluding the high contrast because that applies to all):
- adamantine: 
- amordrine: Having the 2 separate colors is slightly weird but I think I could get used to it.
- angmallen: 
- silver: The little round thing that appears on all the tools almost seems to be filled in with a solid color (ironically it doesn't have enough contrast), especially on the pick and hoe. Some other tools have a similar problem.
- atlarus: 
- black steel: 
- brass: 
- bronze: Looks too much like copper because it's too orange, could be more yellow.
- carmot: 
- celenegil: 
- ceruclase: 
- copper: 
- damascus steel: 
- deep iron: Could maybe use some saturation, since black steel is a shinier less saturated version of this.
- desichalkos: 
- electrum: 
- eximite: 
- haderoth: 
- hepatizon: Is too shiny and pinkish and as a result looks almost exactly like infuscolium
- ignatius: Is too yellowish/goldish, midasium should looks like this.
- inolashite: 
- kalendrite: 
- midasium: Is too orangish/fiery, ignatius should look like this.
- mithril: 
- orichalcum: 
- oureclase: Could maybe use some saturation.
- platinum: Could maybe use a little less saturation
- prometheum: 
- quicksilver: 
- sanguinite: The red parts could use some saturation. Ore looks a bit eye burning/oversaturated.
- shadow iron: 
- shadow steel: Looks too much like shadow iron, could use some saturation.
- steel: 
- tartarite: Should be more orange, it's a 1:1 alloy of a red and a yellow material.
- vulcanite: Ore looks a bit eye burning/oversaturated.
- vyroxeres: Ore looks a bit eye burning/oversaturated.

**Comment by Davoleo** [comment] 2019-03-05 11:03
Just wanna make sure that you know that:

The materials aren't grouped up like the old mod anymore, no more fantasy, precious and ecc

I personally like a lot the concept of multiple colors materials

The whole rework point is literally making the texture less plastic-looking and more metallic

The red parts of sanguinite have been changed to look more like blood and to differentiate from other red materials

**Comment by Davoleo** [comment] 2019-03-05 11:04
I'll let Matpac comment the other ones

**Comment by Klazkin** [comment] 2019-03-05 14:23
@RCXcrafter 
This is a bit overwhelming; so let's start with ores :P

The different textures for ores will be coming back, I am thinking of basing them around the mining level of the ore, this would kill two birds with one stone. People will spend less time guessing whether their pick is adequate to mine the ore as well as make the ores look different in general.

The tool handles shouldn't be wooden, that was a choice I made, not a limitation caused by my methods or anything of that sort. I just didn't really like having to work with brown in every colour pallet of every metal. Tho it is less _realistic_...

My responses to all of the **specific** comments on metals:

- amordrine: Well you should, cause if we ever add more metals, odds are they are gonna be dual colour.

- silver: This was a problem with my way of drawing these tools. I did, later on, found a way to avoid this issue.
 In general, I would like to get rid of these repeating patterns on all of the metals like those gem shapes, the only reason they were still there was my trying to stay loyal to some of the OG textures, that opinion quickly changed when I heard that the OG artist (shadowclaimer) also hated those.

- bronze: Making it more yellow would make it look like brass/camrot, I'd rather have it look similar to a metal it's made from.

- deep iron: Agree, tho I wouldn't like it to look too blue, as we might add a diffirent pure blue metal later on, so the change won't be big.

- hepatizon: Well it is made from infuscolium and steel so the fact that it looks similar isn't that big of a deal considering that infuscolium itself can't be used to make anything in the first place. And personally, I find hepatizon colours alright, so If differences will be made then probably to infuscolium.

- ignatius and midasium:  Maybe I did mismatch them, tho I am kind of embarrassed to admit it lol, I will fix it.

- oureclase: Personally, I find the saturation perfectly fine, increasing it might make it too orange. (the mod has plenty of those already)

- platinum: Would make it too similar to ceruclase. 

- sanguinite: Deep red is more representative of blood and flesh, and everything that sangui and hell means. As well as I don't want it to be just a pure red metal with golden detail as that would somewhat imply of it being an adamantium alloy. 

- shadow steel: Will make it look like damascus, better to reduce saturation on shadow iron, if the problem is that they look too similar.

- tartarite: There are plenty enough of orange metals, and I personally find this shade much more attractive in contrast with dark grey, even if it is less _realistic_.

- vulcanite: Will be fixed.

- vyroxeres: Will be fixed.

You might have noticed that I have been avoiding talking about contrast, well it's because I don't want to be constantly walking in circles, as I am sure you already noticed there are people who prefer these high contrast textures. None of the textures and the decisions made were exactly "rash", we did take our time to discuss these. I am not using their opinions as excuses to not work on improving them. I will improve them. Although, if there will be any changes they aren't going to be major and will take a lot more time than you might think. As fixing them will require me to convert all of the textures to a more general format, not with using my silly techniques and methods. I planned to do this at some point anyway but didn't have a good enough reason to change all of the 600+ textures, again.

You might be wondering why I'd do it like this in the first place, truth be told this whole thing was my first time actually drawing anything but stupid doodles. At the start - I had little to no knowledge about properly drawing these kinds of things. So I used what I knew from graphical design to assist me as much as possible. Looking back I am quite surprised that I got to work on this project in the first place. 

I thank you for your constructive criticism as there is nothing more an artist such as myself can appreciate more. I won't be able to provide you with source files since I guess I'll have to be changing lots of things anyway. It is sad to admit that none of these changes will you see in the next update or even the update after it, as I have a pretty busy lifestyle, especially during this time of year and this is just one of my many hobbies. (TL;DR we're probably talking months here)

None of this is set in stone, If there is something I missed, let me know.

**Comment by RCXcrafter** [comment] 2019-03-05 15:37
I like the idea of categorizing the ores by mining level. Personally I like the brown sticks because it adds a little color variation that you'd otherwise only have on multicolored materials.

The bronze is a little tricky because if you shift the hue it does indeed become brass, I think reducing the saturation to make it browner works relatively well. I also didn't realize the recipe for hepatizon changed to infuscolium + steel.

If you want, I'd be happy to help because this is a pretty big task.

**Comment by Davoleo** [comment] 2019-03-05 17:06
We think that vyroxeres should be left as is, especially because often poison is linked to bright and saturated colours
What do u think about it?

**Comment by RCXcrafter** [comment] 2019-03-05 17:47
Vyroxeres looks pretty good as it is, the dust has a little too much contrast but the rest looks good.

**Comment by Klazkin** [comment] 2019-03-05 17:51
@Davoleo 
The reason that Nether Ores have so much contrast and have that "glowing" effect is because unlike stone, netherrack has a very rough and fairly colourful texture. Which makes it hard to notice ores like sanguinite or shadow iron, and in general nether ores were actually painful for my eyes to look for and tell apart. That's why new ones have so much colour. 

@RCXcrafter 
Currently, I have a few other things I need to finish for this mod before I begin preparation for texture rework 2.0. If I find anything I can ask you to do I will surely contact you on discord (Matpac#8102), tho I don't promise it will be anything exciting. Likely just helping me extract textures into a separate file from a large sheet of sprites. 

P.S. I only use Paint.NET

**Closed** 2019-05-28 17:23 UTC
Labels: minor issue, suggestion
