### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Kasia1403** [Davoleo/Metallurgy-4-Reforged#358] opened 2022-04-29 05:21 UTC
https://paste.ee/p/2iXcs

**Comment by Davoleo** [comment] 2022-04-29 07:54
Duplicate of #357
this will be fixed in the next patch release that I'll release soon

**Comment by Kasia1403** [comment] 2022-04-29 14:46
When will be this bugfix release ? I just can't wait !

**Comment by Kasia1403** [comment] 2022-04-29 15:31
It also happens when I hit iron golem.

**Comment by Kasia1403** [comment] 2022-04-29 18:07
Oh no, after downgrading to lower wersion this crash ( this time with Silent's Gems ) appears :

https://paste.ee/p/jhnyL

**Comment by Davoleo** [comment] 2022-05-01 13:22
> When will be this bugfix release ? I just can't wait !

@Kasia1403 
Please be patient, I also have life and uni matters I should attend, I'll try to release a patch as soon as I can

**Closed** 2022-05-01 15:21 UTC
Labels: bug, duplicate
