### ISSUE TITLE
Player tick crash when wearing full platinum armor

### ISSUE THREAD

**Issue by Druwan-ctrl** [Davoleo/Metallurgy-4-Reforged#306] opened 2021-01-07 18:29 UTC
### General Information

**Describe the bug:**
Wearing the full platinum armor makes the player crash

**To Reproduce:**
1. Wear the armor
2. Crash
3. Call the admin to modify the NBT
4. Profit

**Expected behavior:**
Apply the night vision bonus

***

### Environment Versions

**Versions:**
- Metallurgy: Metallurgy-4-Reforged-1.2.1
- Other mods you think could cause issues: spongeforge-1.12.2-2838-7.3.0 (not the culprit here, but notable)
- Forge: forge-1.12.2-14.23.5.2854
- Minecraft: 1.12.2

***

### Logging Information
[Debug](https://pastebin.com/jSku678W)

**Comment by Davoleo** [comment] 2021-01-07 21:07
Couldn't reproduce the actual crash but I've just removed the function call that caused it.
It should be fixed in the next patch version (1.2.3) please tell me if the issue is fixed whenever you have the time to test it.

**Closed** 2021-01-09 12:05 UTC
Labels: bug
