### ISSUE TITLE
Crash with Better With Mods - Report attached

### ISSUE THREAD

**Issue by Xorbah** [Davoleo/Metallurgy-4-Reforged#141] opened 2019-04-20 13:15 UTC
Title. Using Forge 814 for 1.12.2.

[crash-2019-04-20_08.12.57-server.txt](https://github.com/Davoleo/Metallurgy-4-Reforged/files/3100141/crash-2019-04-20_08.12.57-server.txt)

**Comment by Davoleo** [comment] 2019-04-20 13:16
what mod version are you playing on?

**Comment by Davoleo** [comment] 2019-04-20 13:19
sorry, just saw it on the crash report, I'll look into this issue, even if I thought I had fixed it in #114

**Comment by Davoleo** [comment] 2019-04-20 13:53
I can't reproduce this crash
both in old and in new worlds I get this message
and when I use the gauntlet the gauntlet doesn't crash 

![image](https://user-images.githubusercontent.com/24458276/56458246-76b64380-6384-11e9-8584-c8a253bc3cf2.png)

**Comment by Xorbah** [comment] 2019-04-20 14:15
For some reason if I enable the HCChickens option in the better with mods
config it works. If it's disabled it crashes.

**Comment by Davoleo** [comment] 2019-04-20 14:42
Will be fixed once and for all in the next version (0.2.0)

**Closed** 2019-04-20 22:10 UTC
Labels: bug, fixed/implemented in dev

**Comment by HurtsAsHell** [comment] 2019-05-05 18:00
If you have the BWW installed, unfortunately you will not be able to use the glove because it will be disabled automatically so as not to crash.

The bug is not our own.


Enable the HCChickens option in the better with mods config to fix it or remove BWM
