### ISSUE TITLE
[1.12.2] Entities wearing full Shadow Steel armor may disappear when you hit them with tinkers tools.

### ISSUE THREAD

**Issue by Z-Tunic** [Davoleo/Metallurgy-4-Reforged#359] opened 2022-04-29 13:06 UTC
Minecraft: 1.12.2
Forge: 14.23.5.2860

Mods: 9
ActuallyAdditions-1.12.2-r151-2
conarm-1.12.2-1.2.5.10
jei_1.12.2-4.16.1.302
libnine-1.12.2-1.2.0
Mantle-1.12-1.3.3.55
Metallurgy-4-Reforged-1.3.2
tconevo-1.12.2-1.0.44
TConstruct-1.12.2-2.13.0.183
totaltinkers-0.6.0

Log:
[latest.log](https://github.com/Davoleo/Metallurgy-4-Reforged/files/8590758/latest.log)

=====

No crash report... unless you have Vanillafix then you'll get the report but it appeared in the log when I attacked a zombie pigman wearing full Shadow Steel Armor with Shurikens from Tinkers Construct and a Dagger from Total Tinkers. Should the error occur... the entity that was being attacked will just... disappear.

It might be trait/modifier-related or it might be due to bonus damage hits being applied alongside the main damage. This is what I had on these tools at the time when the error occurred...

(Shuriken)
"Diamatine Knife Blade"
Crystalline: Deal extra damage depending on tool durability, damage lowers as the durability decreases.
Aftershock: Deal extra magic damage if you attack isn't on 'cooldown', aka spam-clicking.

"Cactus Knife Blade"
Prickly: Deals a little bonus damage that ignores armor.
Spiky: Blocking or getting hurt deals damage to the attacker.

"Platinum Knife Blade"
Deadly Precision: Critical hits deal more damage.
Cold-Blooded: Inflict 50% more damage to entities at full health.

"Bone Knife Blade"
Splintering: Target takes 0.5 more damage, up to a total of 2.5 which is 5 stacks.
Fractured: Increases the Tool's Attack Damage

Unbreakable: Tool doesn't lose any durability.
Fiery: Sets the target on fire upon hit, as well as dealing bonus fire damage.

-

(Dagger)
"Bone Tool Rod"
Fractured: Increases the Tool's Attack Damage

"Steel Knife Blade"
Stiff: Blocking reduces the damage taken further.
Sharp: Causes targets to bleed, suffering damage overtime.

"Manyullyn Crossguard"
Cold-Blooded: Inflict 50% more damage to entities at full health.

Unbreakable: Tool doesn't lose any durability.
Fiery: Sets the target on fire upon hit, as well as dealing bonus fire damage.

=====

Note:
Aftershock Trait can bypass iframes... so a shuriken for example can hit entities regardless if they are in the middle of their iframes if you spam throw it.

Dagger Tool has roughly half the iframe timer when attacking entities with it.

Aftershock, Prickly & Fiery deal separate damage splats which appear alongside the main damage splat, so if you had these traits/modifiers on a tool, you can hit an entity pretty much 4 times in one attack. In the case of the shuriken tool due to it's traits/modifiers... I hit 10, 2, 2 and 1 with just one throw, at least what ToroHUD showed me with it's damage particles.

**Comment by Davoleo** [comment] 2022-04-29 13:12
Duplicate of #357

**Comment by Davoleo** [comment] 2022-05-01 15:22
Should be fixed in 1.3.3 (Feel free to comment here if you're still experiencing something similar)

**Closed by Davoleo** 2022-05-01 15:22 UTC
Labels: bug, duplicate
