### ISSUE TITLE
Full set of Krik armor does not give you its effect

### ISSUE THREAD

**Issue by Venom31** [Davoleo/Metallurgy-4-Reforged#289] opened 2020-09-20 18:21 UTC
### General Information

**Describe the bug:**
Krik armor says on the tin that it gives "weight controlled flight", but does nothing special. This is the first time I ever play with it, so apologies in advance if I got it wrong.

**To Reproduce:**
1. Get a full set of Krik armor and equip it. A vertical bar appears on the bottom right with an orange marker, presumably the current Y limit marker.
2. (Optional) Empty your inventory to maximize Y limit?
3. Press UP and DOWN arrow keys to apply armor effect (up to a certain Y limit?).

**Expected behavior:**
The player character would float up to certain Y limit when pressing UP and descend when pressing DOWN.

**Actual behavior:**
The vertical bar fills with green dots up to the orange marker when repeatedly pressing UP, empties when repeatedly pressing DOWN, but nothing else happens.

***

### Environment Versions

**Versions:**
- Metallurgy: 0.3.2
- Other mods you think could cause issues: IDK
- Forge: 1.12.2-14.23.5.2847
- Minecraft: 1.12.2
- Modpack (if available): Material Energy^5: Entity - 1.1.1

***

**Crash Report (if available): No crash**

***

### Additional Information

**Additional context (optional):**
Performed in the End dimension, as that's where the ME^5 story takes place. But that shouldn't be a problem?

**Comment by Davoleo** [comment] 2020-10-01 12:45
ok so this sounds like it's a Duplicate of #234 
Update Metallurgy, at least to 0.3.3 where this bug was fixed

**Closed by Davoleo** 2020-10-01 12:45 UTC
Labels: bug, duplicate

**Comment by Venom31** [comment] 2020-10-04 14:33
Great, I'll link the modpack creators to this, so they can see a need to update.

**Comment by OmegaCenti** [comment] 2020-10-05 20:34
Was notified of the comment, I, the commenter on the issue have seen your latest comment and your update in this issue thread, lets see what GreNinjaSan has to say in his discord
