### ISSUE TITLE
Crash while spawning on land (LitV

### ISSUE THREAD

**Issue by Councilor** [Davoleo/Metallurgy-4-Reforged#152] opened 2019-05-05 15:04 UTC
**Describe the bug**
Upon Loading into a world and spawning on land, the game will crash.

**To Reproduce**
1. create a new minecraft world
2. hope to spawn on land
3. it will crash several seconds after spawnining in

**Expected behavior**
not crashing

**Screenshots**

**Versions:** _DO NOT write "the latest"_
- Metallurgy 4: Reforged: 0.2.0
- Forge: 14.23.5.2768
- Minecraft: 1.12.2
- Modpack _(if avaliable)_: Modified Life in the Village (Tinker's construct 2.12.0.135, Tinkers Tool Leveling 1.1.0, Conarm 1.2.3.4, Armory Expantion 1.1.10c, Metallurgy 4: Reforged
- Conflicting mod _(if regarding mod integration)_: Metallurgy 4: Reforged, Better With Mods, Open Terrain Generation 
- Other mods you think could cause issues:  

**Crash Report** _(if avaliable)_ 
https://paste.dimdev.org/tuwarifepi.mccrash

**Log** _(if needed)_
**Use [gist](https://gist.github.com) or spoilers or [paste.ee](https://paste.ee) or [pastebin](https://pastebin.com)**

**Additional context** _(if needed)_
Mantle was updated to 1.3.3.49 from the original modpack's older version

**Comment by Late-Night** [comment] 2019-05-05 16:20
>otg
there's your problem
just get BoP

**Comment by Councilor** [comment] 2019-05-05 16:25
otg is part of the modpack

**Comment by Davoleo** [comment] 2019-05-05 16:36
Can you perhaps try and enable HCChicken from BWM? @Councilor

**Comment by Councilor** [comment] 2019-05-05 16:50
that fixes it, if anything changes i'll let you know.

**Comment by Davoleo** [comment] 2019-05-05 16:51
ok then this is a
Duplicate of #141

**Closed** 2019-05-28 17:22 UTC
Labels: bug, duplicate, fixed/implemented in dev
