### ISSUE TITLE
Pewter, Metallurgy-4-Reforged, TConstruct incompatability.

### ISSUE THREAD

**Issue by SashaIndustries** [Davoleo/Metallurgy-4-Reforged#335] opened 2021-08-29 11:08 UTC
### General Information
1.12.2
i9 10980XE
2x4x64GB RAM
3xEVGA RTX 2080SS VMLINK (SLI disabled for Minecraft)

**Describe the bug:**
Pewter conflicts with Osmium
**To Reproduce:**
As far as I'm aware adding Metallurgy 4: Reforged, Pewters and TConstruct causes the issue.

1. Install Forge
2. Install Metallurgy 4:Reforged
3. Install TConstruct
4. Press the play button
5. Crashes before main menu during registration

***

### Environment Versions

**Versions:**
-Metallurgy-4-Reforged-1.2.10.jar
-Pewter-1.4.3.jar
-TConstruct-1.12.2-2.13.0.183.jar
- Forge:14.23.5.2855
- Minecraft 1.12.2
- Modpack (if available):My own custom one.

***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**

**Crash Report (if available):**

No point reuploading when the exact crash already exists
https://github.com/Davoleo/Metallurgy-4-Reforged/issues/192#issue-470607159
**Latest Log (if necessary):**

***

### Additional Information
**Screenshots (if available):**

**Additional context (optional):**

This isn't that hard of an issue to solve.
Template to solve it
Does Metallurgy-4-Reforged have more content for Osmium then Pewter?
If yes ask the maker of Pewter to make a patch that disables Osmium when Metallurgy-4-Reforged is detected
If no make a patch that disables Osmium for Metallurgy-4-Reforged if Pewter is enabled
If possible prevent is being a requirement to add the materials if material already exists.

**Comment by Davoleo** [comment] 2021-08-29 11:39
Hey, thanks for reporting this issue
This is indeed caused by pewter not disabling osmium when Metallurgy is loaded, they don't mention Osmium on their CF page so I'm guessing the went to implement mekanism integration and didn't update their mod description, furthermore the link to the source code is broken so I can't really access their source code, to know the exact place where this breaks.

In our mod we already check if any of the mods that were loaded before metallurgy already integrate their metal with Tinkers construct and in that case we restrain from loading that material integration, in this case though pewter loads after metallurgy and doesn't make this check in their code probably.

Although this is something that should be fixed on Pewters side, since the mod's not seen any update since 2018 and the latest comments on CF by the author suggest that they will drop 1.12.2 to work on later versions of minecraft, I'll create a patch to handle this specific case: `pewter is in the game -> metallurgy will never load osmium integration for TiCon`
_(Just wanted to explain that this is just a patch on our side and doesn't change the fact Pewter could be crashing with other mods that add TiCon Osmium Integration themselves)_

I apologise for the answer that was given in the old thread about this issue.

**Comment by Handeril** [comment] 2021-08-29 16:36
Please add Prometheum to the list as well [if not already implemented] for if TAIGA is loaded.

If not disabled, it leads to a "soft" material conflict in which both versions exist, but only one gets all the smelting recipes.

**Comment by SashaIndustries** [comment] 2021-08-29 17:24
Thank you for such a quick reply is great to see people are enthusiastic with this project and lovely to see some good people online, thank you very much for all your efforts in fixing this and keeping this alive I@m sure many appreciate it greatly :)
Tried to look for Pewters myself but it was a struggle to get anywhere in finding them

**Comment by RCXcrafter** [comment] 2021-08-30 07:06
Personally I think the solution to this should be to disable the material in the metallurgy config or the pewter config depending on which material is preferred. Always disabling osmium when pewter is installed would make it impossible to use the material from metallurgy when pewter is installed.

**Comment by Davoleo** [comment] 2021-08-30 08:05
I get your point.
But it's kind of hard when most people don't even look at the config before reporting, or before giving up to play with a certain mod if it crashes.
if I implement this, it's going to be a strict check (since I've discovered mekanism is the actual cause of the crash together with pewter) so ideally I'll check if both mods are loaded and in that case I won't load osmium compat at all

Although I surely won't do  the same thing for TAIGA and Prometheum, since it's not a crash, but just a material conflict users can just disable the material in one of the two mods

both TAIGA and Pewter are mods that didn't get updates in a long time, so I'm not hoping in any collab with them to solve these issues
but @RCXcrafter if you know a way to avoid abrupt crashing and tell end users how to solve this conflict through we could avoid creating an exception for osmium at all

**Comment by RCXcrafter** [comment] 2021-08-30 11:42
I don't have a better solution, for my tinkers addon I decided not to automaticaly disable any of my materials and I had to explain to a lot of people how to use the config so I understand why you've decided to do it this way. Maybe a config option that disables checking for existing materials could be a way to still allow users to choose. Though considering it requires both pewter and mekanism it's not as big of an issue as I originally thought.

**Comment by Davoleo** [comment] 2021-08-30 16:17
ok for the moment I'll keep this as is, while a crash is a serious issue, there is a workaround you can do to fix this issue by yourself, and as RCX stated disabling osmium entirely might be overkill and unwanted for certain players.
I'll however re-consider adding a patch to disable osmium automatically if multiple other users complain about this issue.

## Steps to fix this issue:
- open `instance/config/metallurgy_reforged/general.cfg`
- add `osmium` to the correct config entry which is shown here below
```cfg
    # Add a material in this array to blacklist it during game boot - material name format is "snake_case" 
    S:"Tinker Materials Blacklist" <
     >
```

**Closed** 2023-02-25 13:00 UTC
Labels: bug, external cause
