### ISSUE TITLE
Construct's Armory with Vulcanite parts freezing the game

### ISSUE THREAD

**Issue by YukiD1st** [Davoleo/Metallurgy-4-Reforged#169] opened 2019-06-15 23:05 UTC
**Describe the bug**
If I make any armor (chest, helmet, boots or leggins) using a piece of Vulcanite with any TWO other different materials, as soon as you put on the armor that you made, not just the game, but the entire server freezes.

**To Reproduce**
1. Make an armor piece using three different materials, one of this materials needs to be Vulcanite.
2. When you complete the armor piece, simply put it on, and the game will freeze.

**Expected behavior**
The game shouldn't freeze because I combined 3 different materials, I guess.

**Versions:** _DO NOT write "the latest"_
- Metallurgy 4: Reforged: Metallurgy-4-Reforged-0.2.0
- Forge: forge-1.12.2-14.23.5.2838
- Minecraft: 1.12.2
- Modpack : https://drive.google.com/file/d/1Focf6I6SczV9fhzR1Zovhx_EfZDbTZlw/view
- Conflicting mod : conarm-1.12.2-1.2.4
- Other mods you think could cause issues: TConstruct-1.12.2-2.12.0.135

**Comment by Davoleo** [comment] 2019-06-15 23:21
Duplicate of #147

**Closed** 2019-06-19 10:21 UTC
Labels: bug, duplicate, fixed/implemented in dev
