### ISSUE TITLE
Enderman do not Attack when Looked At

### ISSUE THREAD

**Issue by ctwagon** [Davoleo/Metallurgy-4-Reforged#297] opened 2020-11-22 18:35 UTC
### General Information

**Describe the bug:**
Enderman do not attack a player that looks at them.

**To Reproduce:**

1. Create a creative mode world with cheats enabled
2. Set time to night
3. Spawn an enderman
4. Set gamemode to survival
5. Look at enderman in eyes/midsection

**Expected behavior:**

The enderman should start attacking the player.

***

### Environment Versions

**Versions:**
- Metallurgy: 1.1.2
- Conflicting mod (if regarding mod integration): N/A
- Other mods you think could cause issues: N/A
- Forge: 14.23.5.2847
- Minecraft: 1.12.2
- Modpack (if available): N/A

***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**

**Crash Report (if available):**

**Latest Log (if necessary):**

***

### Additional Information
**Screenshots (if available):**

![2020-11-22_12 21 50](https://user-images.githubusercontent.com/8313471/99913791-371daf00-2cbf-11eb-8bc1-5d4cf33d190e.png)

**Additional context (optional):**

**Comment by ctwagon** [comment] 2020-11-23 16:32
Tested in Metallurgy 1.2.0-beta.1 and is still an issue.

**Comment by Davoleo** [comment] 2020-11-24 15:25
umh, I'm going to need some more context because I can't seem to reproduce it in my dev env: https://streamable.com/hpgqiz

**Comment by Davoleo** [comment] 2020-11-24 16:14
Ok I've found the cause of this, apparently you can only reproduce this bug while using the built jar version of the mod, I'll try releasing a fix for this in the next version

**Closed** 2020-11-24 16:47 UTC
Labels: (╯°□°）╯︵ ┻━┻, bug
