### ISSUE TITLE
Crash on ticking player

### ISSUE THREAD

**Issue by ricemyelii** [Davoleo/Metallurgy-4-Reforged#182] opened 2019-06-30 08:11 UTC
**Describe the bug**
game crash when ticking player on world startup

**To Reproduce**
loading/creating a world

**Screenshots**

**Versions:** _DO NOT write "the latest"_
- Metallurgy 4: Reforged: 0.2.1
- Forge: 1.12.2-14.23.5.2838
- Minecraft: 1.12.2
- Modpack _(if available)_: none
- Conflicting mod _(if regarding mod integration)_: lemonlib
- Other mods you think could cause issues: any mods that require lemonlib

**Crash Report** _(if available)_
https://pastebin.com/5MYCyA0h

**Log** _(latest.log)_ 
https://pastebin.com/t5fLQAvq

**Additional context** _(if needed)_
Never had this problem before Metallurgy 4 0.2.1

**Comment by Davoleo** [comment] 2019-06-30 08:31
Duplicate of #178

**Closed** 2019-07-02 08:45 UTC
Labels: bug, duplicate, fixed/implemented in dev
