### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Kasia1403** [Davoleo/Metallurgy-4-Reforged#372] opened 2023-02-03 13:02 UTC
To make Metallurgy Reforged not crash with Chocolate Quest Repoured mod's dungeon protection. 

[crash-2023-02-03_13.20.38-server.txt](https://github.com/Davoleo/Metallurgy-4-Reforged/files/10579074/crash-2023-02-03_13.20.38-server.txt)

**Comment by Davoleo** [comment] 2023-02-03 14:47
Duplicate of #371

**Closed by Davoleo** 2023-02-03 14:47 UTC
Labels: duplicate
