### ISSUE TITLE
Pewter Crash With Metallurgy 4, TAKE 2

### ISSUE THREAD

**Issue by TBiscuit1** [Davoleo/Metallurgy-4-Reforged#193] opened 2019-07-20 00:37 UTC
**Describe the bug**
The game crash with pewter and metallurgy 4 together

**To Reproduce**
Have Pewter and Metallurgy 4 together

**Screenshots**
Screenshot is not really possible

**Versions:** _DO NOT write "the latest"_
- Metallurgy 4: Reforged: Any
- Forge: Any
- Minecraft: 1.12.2
- Modpack _(if available)_: Only the combination of the two mod work
- Conflicting mod _(if regarding mod integration)_: Pewter
- Other mods you think could cause issues:  No one

**Crash Report** _(if available)_
[crash-2019-07-19_19.24.45-client.txt](https://github.com/Davoleo/Metallurgy-4-Reforged/files/3413083/crash-2019-07-19_19.24.45-client.txt)

**Log** _(latest.log)_ 
[2019-07-19-7.log](https://github.com/Davoleo/Metallurgy-4-Reforged/files/3413085/2019-07-19-7.log)

**Additional context** _(if needed)_
Tinker material that Metallurgy are the problem. By disabling the tinker integration (In the config) It doesn't crash, also in the crash report, it looks like osmium is the problem (Metallurgy add osmium but it's not a tinker material O.o)

**Comment by TBiscuit1** [comment] 2019-07-20 00:38
OOPS I posted a log and not the latest log (But it's the same log)

**Comment by HurtsAsHell** [comment] 2019-07-20 00:41
Okay, the problem is that the pewter don't check if the material is already registed.

Have you already reported this bug to the Owner of Pewter?

**Comment by TBiscuit1** [comment] 2019-07-20 00:46
Yes I made the report first with pewter and to be sure if you could do something on this, I reported the issue here too

**Comment by HurtsAsHell** [comment] 2019-07-20 00:47
Unfortunately we can't do anything about this, the problem happens because the mod is recorded after mine. Only one check must be added to fix it

**Comment by HurtsAsHell** [comment] 2019-07-20 00:47
Please, report here the issues of the other github repository

**Comment by TBiscuit1** [comment] 2019-07-20 01:05
https://github.com/ejektaflex/Pewter/issues/78 Here is the issue (I posted this one in the pewter one

**Comment by HurtsAsHell** [comment] 2019-07-20 01:06
thanks

**Comment by HurtsAsHell** [comment] 2019-07-29 10:23
I close the issues for the moment, for other question, write here

**Closed by HurtsAsHell** 2019-07-29 10:23 UTC
Labels: bug, other mod

**Comment by border999** [comment] 2019-10-12 05:47
@HurtsAsHell the point still stands this is an issue, has there been any development on this since july?
